from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

import numpy as np

from core.loader import load_dat, resolve_dat_y_axis
from core import data_io


class DatLoaderTests(unittest.TestCase):
    def test_loads_colormap_in_internal_gate_by_energy_orientation(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "map.dat"
            path.write_text(
                "# generated by Origin-compatible exporter\n"
                "Photon energy(eV)\t-1\t2\n"
                "1\t10\t20\n"
                "2\t30\t40\n",
                encoding="utf-8",
            )
            cube = load_dat(path)
            np.testing.assert_allclose(cube.energy, [1.0, 2.0])
            np.testing.assert_allclose(cube.gate, [-1.0, 2.0])
            np.testing.assert_allclose(cube.Z, [[10.0, 30.0], [20.0, 40.0]])

    def test_loads_one_gate_curve_and_nan(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "curve.dat"
            path.write_text(
                "Photon energy(eV)\t0\n1\tnan\n2\tinf\n",
                encoding="utf-8",
            )
            cube = load_dat(path)
            self.assertEqual(cube.Z.shape, (1, 2))
            self.assertTrue(np.isnan(cube.Z[0, 0]))
            self.assertTrue(np.isinf(cube.Z[0, 1]))

    def test_missing_sidecar_uses_neutral_y_label(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "neutral.dat"
            path.write_text("Photon energy\t0\n1\t2\n", encoding="utf-8")
            cube = load_dat(path)
            self.assertEqual(cube.gate_label, "Y")
            self.assertEqual(cube.gate_unit, "")
            self.assertEqual(cube.y_axis_semantic, "")

    def test_sidecar_restores_supported_labels(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "processed.dat"
            path.write_text("Photon energy(eV)\t0\n1\t2\n", encoding="utf-8")
            sidecar = path.with_suffix(".metadata.json")
            sidecar.write_text(
                json.dumps({
                    "operation": "DR/R",
                    "plot": {
                        "title": "Restored title",
                        "ylabel": "Magnetic field (T)",
                        "cbar_label": "dR/R",
                        "y_unit": "T",
                        "cmap": "RdBu_r",
                    },
                }),
                encoding="utf-8",
            )
            cube = load_dat(path)
            self.assertEqual(cube.title, "Restored title")
            self.assertEqual(cube.gate_label, "Magnetic field (T)")
            self.assertEqual(cube.cbar_label, "dR/R")
            self.assertEqual(cube.gate_unit, "T")
            self.assertEqual(cube.plot_metadata["cmap"], "RdBu_r")

    def test_dat_y_axis_choices_do_not_change_numeric_coordinates(self) -> None:
        choices = {
            "Doping": ("Doping", "cm^-2", "doping"),
            "Electric field": ("Electric field", "V/m", "electric_field"),
            "Gate voltage": ("Gate voltage", "V", "gate_voltage"),
            "Custom": ("My axis", "arb.", "custom"),
        }
        for choice, expected in choices.items():
            self.assertEqual(resolve_dat_y_axis(choice, custom_label="My axis", custom_unit=expected[1]), expected)
        self.assertEqual(resolve_dat_y_axis("Y"), ("Y", "", "y"))

    def test_plotmeta_sidecar_is_supported(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "processed.dat"
            path.write_text("Photon energy\t0\n1\t2\n", encoding="utf-8")
            Path(f"{path}.plotmeta.json").write_text(
                json.dumps({"plot": {"title": "Plotmeta"}}), encoding="utf-8"
            )
            self.assertEqual(load_dat(path).title, "Plotmeta")

    def test_missing_or_malformed_sidecar_does_not_block_import(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "legacy.dat"
            path.write_text("Photon energy\t0\n1\t2\n", encoding="utf-8")
            path.with_suffix(".metadata.json").write_text("{bad", encoding="utf-8")
            cube = load_dat(path)
            self.assertEqual(cube.title, "legacy")
            self.assertEqual(cube.cbar_label, "Imported DAT")

    def test_rejects_ragged_or_non_numeric_rows(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            ragged = Path(tmp) / "ragged.dat"
            ragged.write_text("Photon energy\t0\t1\n1\t2\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "expected 3"):
                load_dat(ragged)
            invalid = Path(tmp) / "invalid.dat"
            invalid.write_text("Photon energy\t0\nnot-a-number\t2\n", encoding="utf-8")
            with self.assertRaisesRegex(ValueError, "non-numeric"):
                load_dat(invalid)

    def test_existing_pl_loader_dispatches_dat_and_discovers_it(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            folder = Path(tmp)
            path = folder / "processed.dat"
            path.write_text("Photon energy\t0\n1\t2\n", encoding="utf-8")
            self.assertIn("processed.dat", data_io.list_map_input_files(str(folder)))
            cube = data_io.load_pl_cube(str(folder), path.name)
            np.testing.assert_allclose(cube.Z, [[2.0]])


if __name__ == "__main__":
    unittest.main()
